### ISSUE TITLE
Memory & energy footprint

### ISSUE THREAD

**Issue by lukeswitz** [lukeswitz/haven#21]
Ongoing list of opportunities for fixes:

#274
`java.lang.OutOfMemoryError:Failed` to allocate a 8294412 byte allocation with 6502296 free bytes and 6MB until OOM
` at org.havenapp.main.sensors.media.ImageCodec.lumaToGreyscale(ImageCodec.java:44)
` at org.havenapp.main.sensors.media.ImageCodec.lumaToBitmapGreyscale(ImageCodec.java:55)
 `org.havenapp.main.sensors.media.MotionAsyncTask.run(MotionAsyncTask.java:102)`

#257 OOM grayscale bitmap 

#258
`android.app.ServiceConnectionLeaked: Activity org.havenapp.main.MonitorActivity has leaked ServiceConnection org.havenapp.main.sensors.motion.Preview$1@2cf2e148 that was originally bound here
                      at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:965)
   `

**Comment by lukeswitz** [comment]
Change Preview line 191 to reflect:
```
List<Size> supportedPreviewSizes = camera.getParameters().getSupportedPreviewSizes();
parameters.setPreviewSize(supportedPreviewSizes.get(0).width,supportedPreviewSizes.get(0).height);

/**
                 * The above seems to work much faster
                List<Size> sizesPreviews = parameters.getSupportedPreviewSizes();
                Size bestSize = sizesPreviews.get(0);

                for (int i = 1; i < sizesPreviews.size(); i++) {
                    if ((sizesPreviews.get(i).width * sizesPreviews.get(i).height) >
                            (bestSize.width * bestSize.height)) {
                        bestSize = sizesPreviews.get(i);
                    }
                }

                parameters.setPreviewSize(bestSize.width, bestSize.height);
 **/

```
```

**Comment by n8fr8** [comment]
I've been working with this library on another project:
https://github.com/siralam/CameraViewPlus

and it works quite well for managing max resolutions, etc. It also uses the Camera2 API. I may dig into using it here.

**Comment by lukeswitz** [comment]
I’ll have a look on break, thanks!

**Comment by lukeswitz** [comment]
Very much improved in build 115, closing
